// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcvoxoiluxempncovsck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhjdm94b2lsdXhlbXBuY292c2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDA5NjksImV4cCI6MjA2NTgxNjk2OX0.IFWOG5Ro9wVLMQf6spt7U14bS60aXPKAsWKbYZXRnzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);